GET http://127.0.0.1:8000/products/ HTTP/1.1

###

GET http://127.0.0.1:8000/products/2/ HTTP/1.1

###
DELETE http://127.0.0.1:8000/products/1/ HTTP/1.1


###

PUT http://127.0.0.1:8000/products/2/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwi...

{
    "name": "Television",
    "price": 300.00,
    "stock": 14,
    "description": "An amazing new TV"
}



###
POST http://127.0.0.1:8000/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyNzkzMzgwLCJpYXQiOjE3NzI3OTMwODAsImp0aSI6ImM3MTZlOTk3NmU5NjRhMTVhMGVkOGRhN2RiZTUzMmVmIiwidXNlcl9pZCI6IjEifQ.OLXuGUfFKNeHildR-q0GpggR-w277gqirNkKZvpMBjw

{
    "name": "Television",
    "price": 300.00,
    "stock": 14,
    "description": "An amazing new TV"
}

###

POST http://127.0.0.1:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "admin123",
    "password": "admin123"
}

###
POST http://127.0.0.1:8000/api/token/refresh/ HTTP/1.1
Content-Type: application/json

{
   "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3Mjg2MDAzOSwiaWF0IjoxNzcyNzczNjM5LCJqdGkiOiJlNGQyNWIzNThjNWQ0YmNkOTI1NTQ1MGM3ZTQ4MWQyZiIsInVzZXJfaWQiOiIxIn0.GJSDCZhP0tSHkooITyaiXddheORorM4r5zLsJ8F7P6g"
}

###
GET http://127.0.0.1:8000/orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyODkxOTg5LCJpYXQiOjE3NzI4OTE2ODksImp0aSI6ImEzOGJiNGVjNzdkNzQ3MGE4ZWE3ZGM5MDdiMjE1YzAyIiwidXNlcl9pZCI6IjEifQ.riQyej2YMLai8JEcdY3D5JvhySBHvfsamdhDeC7g3tc

###
POST http://127.0.0.1:8000/orders/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyOTQ1NDg5LCJpYXQiOjE3NzI5NDUxODksImp0aSI6Ijc1ZTJkNDFiZWFlMTRhOTNiODA3YTc0MzczYTA0YmYyIiwidXNlcl9pZCI6IjIifQ.fuFAWE0CNo5aaWJwodzWyr_LwYW8Vh6aWY5KAEXUFSc

{
    "status": "Pending",
    "items": [
        {
            "product": 2,
            "quantity": 3

        },
        {
            "product": 3,
            "quantity": 1
        }
    ]
}

### 
DELETE http://127.0.0.1:8000/orders/34029f42-92ad-42e2-ab82-74e20cb0c190/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyOTUyMTczLCJpYXQiOjE3NzI5NTE4NzMsImp0aSI6IjUwMTBiMTNkNTg1MjRhMzFiNWRiNzUxYzAyNjY5Nzc5IiwidXNlcl9pZCI6IjIifQ.g9NUGgjtUx6avdp1gNcNCwv3WZt5t6aa4OoADTrGNzg